### PR TITLE
WIP Package: traffic stats (installs and views sparklines)

### PR DESCRIPTION
**Pull request by nl0**
Show traffic stats on the package page.

Depends on:
  - ~#587~
  - ~#588~
  - #594 

### TODO

- [x] tweak styling
- [x] intl
- [x] wire up the api
- [x] fill up the sparkline timeseries with zeroes to the fixed length (52)? @akarve 
  - will be done on the API side
- [x] get total installs count somewhere or change display logic to not show it altogether @akarve 
  - will be done on the API side
- [x] wait for the API changes and adjust if necessary

### CODE REVIEW

**Comment by nl0** [comment]
@akarve this one is ready for review. The sparklines are heavily inspired by [npmjs.com](https://www.npmjs.com/package/lodash). It looks like this:

sparklines

**Comment by akarve** [comment]
Cool. I'll tweak colors and styling. You will use the API in #582 which is under review.

**Comment by nl0** [comment]
@akarve i've wired up the api, but there's no total installs count (to be shown when sparkline is not hovered) in the response. also, there's no views data, so i've commented that section out.

**Comment by nl0** [comment]
@akarve also, to keep things consistent i can fill the sparkline with zeroes up to length 52 (a full year), if there's less than 52 items returned by the api

**Comment by akarve** [comment]
API should do all heavy lifting: padding, and grand total installs. I've asked @meffij to update the endpoint.

**Comment by akarve** [comment]
Also, can you bring "view" back? @meffij please give call signatures

**Comment by nl0** [comment]
@akarve done

**Comment by akarve** [comment]
Updated API is here. LMK if it works.
https://github.com/quiltdata/quilt/pull/594

**Comment by nl0** [comment]
@akarve i've adjusted the styling as requested:
screen shot 2018-05-12 at 00 40 56

**Comment by akarve** [comment]
Looks really good; there is a very subtle bug with the Sparkline (or Section) component where, after hover, a very thin line appears far right.

screen shot 2018-05-14 at 3 00 53 pm

**Pull request merged**
