### PR TITLE
Make format a property of data nodes rather than the package.

### PR DESCRIPTION
**Pull request by dimaryaz**
Allows us to have mixed-format packages. Required for package editing to work correctly.

(We'll need to update the server first, though.)

### CODE REVIEW

**Comment by quiltdata** [comment]
Yeah the server should warn if the min version is less than some number or doesn't exist. Maybe the header should contain a version string; worth logging the version to mixpanel as well.

**Comment by dimaryaz** [comment]
Oh damn, didn't think about that. So besides adding a version string, I could split this into two changes: 1) understand new format, and 2) generate new format. Then we could release 1 immediately, and wait with 2. Requires more work, though.

**Comment by akarve** [comment]
why did this fail ci/push?

**Comment by akarve** [comment]
ci/push barfed on all platforms

**Comment by akarve** [comment]
@dimaryaz by generate the format do you mean migrate the package? i don't think we need to worry about that. we should 5xx if we can't deliver the the package to the client though.

**Pull request merged**
