### PR TITLE
Enable SignUp for `mode="OPEN"` only

### PR DESCRIPTION
**Pull request by fiskus**
- [x] [Changelog](CHANGELOG.md) entry (skip if change is not significant to end users, e.g. docs only)

### CODE REVIEW

**Review by nl0 — APPROVED** [review]

**Comment by akarve** [comment]
I think we need something more general here, such as a flag to disable the SignUp route via config.js? @dimaryaz can you comment?

SignUp orthogonal to PasswordAuth, as even SSO stacks can sign up. The condition is more like in "PRODUCT" mode and under certain backend circumstances (sign up disabled, which is the common case) disable the route.

**Review by dimaryaz — DISMISSED** [review]
I think this is correct.

In the past, SSO sign up had a second step, where the user had to enter a username - but that's gone now, so the sign in page is all that's necessary.

**Review by akarve — APPROVED** [review]

**Comment by drernie** [comment]
@sir-sigurd I'm assuming this is obsoleted by open.quilt.bio.  If not, and worth prioritizing, please re-open.

**Comment by sir-sigurd** [comment]
> I'm assuming this is obsoleted by open.quilt.bio

I'm out of the context but don't see a reason why

**Pull request closed without merging**
