### PR TITLE
Buttons refactoring

### PR DESCRIPTION
**Pull request by fiskus**
Changed:
* Buttons "Create package from folder" and "Push to bucket" have icon in wide layouts too. I think it would be consistent (though chosen icon is not optimal)
* Some small flex/margins changes like moving buttons to the next line on small screens (`flexWrap: 'wrap'`, see screenshot)

Refactored:
* Added `components/Buttons/ButtonIconized`, and replace `FileView.AdaptiveLayoutButton`
* Refactor and unify margins for these buttons
* Remove `components/ButtonIcon`. It was used only once, and it's trivial
Screenshot from 2023-01-30 18-27-08

- [x] [Changelog](CHANGELOG.md) entry (skip if change is not significant to end users, e.g. docs only)

### CODE REVIEW

**Review by nl0 — APPROVED** [review]
looks ok, tho i'm a little reluctant about adding a whole new namespace (`components/Button`) for only one export. to me, `components/ButtonIconized` makes more sense at the moment, tho this whole arguments smells of bike-shedding, so whatever

**Comment by fiskus** [comment]
Hmm..., Ok, I'll rename it to ButtonIconized, and move to Buttons again only when there will be one more button reused across app

**Comment by nl0** [comment]
> Hmm..., Ok, I'll rename it to ButtonIconized, and move to Buttons again only when there will be one more button reused across app

As i said, it's not a requirement and you can keep it as is if you feel like it would be better in perspective

**Comment by fiskus** [comment]
I mean, I agree, namespace Buttons will be reasonable when it contains at least two buttons

**Review by nl0 — APPROVED** [review]

**Pull request merged**
