### PR TITLE
upgrade JS stuff 

### PR DESCRIPTION
**Pull request by nl0**
Upgrade lots of stuff, most notable changes:

* webpack@3 & webpack-dev-middleware@2

* react@16

* material-ui@0.20

* styled-components@3

* enzyme@3

* `env` babel presets instead of `latest`

Also, all the dependecnies are now stated with the caret (^) syntax.

Changes introduced to make things work with the updated dependencies:

* use `prop-types` packages

* update webpack configs

* backport some changes from react-boilerplate@3.5

* update code according to the new linting rules

* make test stubs pass

### CODE REVIEW

**Comment by nl0** [comment]
@akarve this one is work in progress, so not expected to be properly runnable)

**Comment by nl0** [comment]
@akarve ok, now it should work. The branch has been rebased onto the latest master. I'll quote the commit message that sums up the changes:

Upgrade lots of stuff, most notable changes:

* webpack@3 & webpack-dev-middleware@2

* react@16

* material-ui@0.20

* styled-components@3

* enzyme@3

* `env` babel presets instead of `latest`

Also, all the dependecnies are now stated with the caret (^) syntax.

Changes introduced to make things work with the updated dependencies:

* use `prop-types` packages

* update webpack configs

* backport some changes from react-boilerplate@3.5

* update code according to the new linting rules

* make test stubs pass

**Comment by akarve** [comment]
Nice. `npm run lint` now works but `npm run build does not`.

- [ ] fix `npm run build`

Here's the error I got:
```
apk-mbp-3:catalog karve$ npm run build

> quilt-catalog@0.0.0 prebuild /Users/karve/code/quilt/catalog
> npm run build:clean


> quilt-catalog@0.0.0 build:clean /Users/karve/code/quilt/catalog
> rimraf ./build


> quilt-catalog@0.0.0 build /Users/karve/code/quilt/catalog
> cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout

Hash: 2613cc93403f1005c8a5                                                    p Version: webpack 3.10.0
Time: 18688ms
                               Asset       Size  Chunks                    Chunk Names
     0.d14c187d470019d0c344.chunk.js     711 kB       0  [emitted]  [big]  
3b45ceb8d3ec8e67d781f4e30fe2b25c.jpg    38.8 kB          [emitted]         
398f721fb279562d5c2bafb6e420bc0f.png    5.33 kB          [emitted]         
e5e05daa7ebdb7a139da4b49d2251dac.png    20.5 kB          [emitted]         
fdb368cc4abf74980af624f5b5527b15.jpg     244 kB          [emitted]         
9eb602f32e9fce869c2009fc6eb63592.png    1.87 kB          [emitted]         
e7bc25f00791efe5f0419a8cd1fe5f96.png    10.7 kB          [emitted]         
f244525a399174334ebbc6cf619a26f6.png    8.34 kB          [emitted]         
6888f949f2285c93d96c7af3f490ceec.png     3.5 kB          [emitted]         
317962ba94a4e642fbc8b11cf78141b1.png    7.41 kB          [emitted]         
                       .htaccess.bin    1.79 kB          [emitted]         
                         favicon.ico    28.7 kB          [emitted]         
                       manifest.json  618 bytes          [emitted]         
                        quilt-og.png    15.8 kB          [emitted]         
90a8829436b1bfac06c56e93ef6e4e9f.png    11.3 kB          [emitted]         
     1.ff9bd9ecd59d653f1cff.chunk.js    96.3 kB       1  [emitted]         
     2.a277cfa5936907b7065d.chunk.js    31.8 kB       2  [emitted]         
     3.3a2316ab7d63a7bcc7d1.chunk.js    20.6 kB       3  [emitted]         
     4.c12deba07d769b6783bc.chunk.js    4.37 kB       4  [emitted]         
     5.75b55f88e1a89faeda86.chunk.js      41 kB       5  [emitted]         
     6.1a35637f1d9c199ce160.chunk.js    4.47 kB       6  [emitted]         
     7.91ae3786c16140407931.chunk.js    2.41 kB       7  [emitted]         
     8.623621b3c1f19ffb8970.chunk.js    24.1 kB       8  [emitted]         
     9.54eee04c9b69011c674a.chunk.js  541 bytes       9  [emitted]         
    10.c6ab9afacbefb34cb5d3.chunk.js    2.47 kB      10  [emitted]         
                          index.html       2 kB          [emitted]         
                           config.js  753 bytes          [emitted]         
                               sw.js  342 bytes          [emitted]         
                     docs/quants.pdf     616 kB          [emitted]  [big]  

ERROR in chunk main [entry]
[name].[chunkhash].js
'import' and 'export' may only appear at the top level (70:6)
|   if (false) {
|     module.hot.accept('./reducers', function () {
|       import('./reducers').then(function (reducerModule) {
|         var createReducers = reducerModule.default;
|         var nextReducers = createReducers(store.asyncReducers);
Child html-webpack-plugin for "index.html":
     1 asset
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! quilt-catalog@0.0.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the quilt-catalog@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karve/.npm/_logs/2018-02-06T18_32_22_345Z-debug.log
apk-mbp-3:catalog karve$ 
```

**Comment by nl0** [comment]
@akarve fixed and rebased. The [bug](https://github.com/webpack/webpack/issues/5663) in webpack's `ModuleConcatenationPlugin` caused build failure, so I had to work around it.

**Comment by akarve** [comment]
- [ ] resolve conflicts with `master` (note that we've deleted `yarn.lock`)

**Comment by nl0** [comment]
@akarve done

**Pull request merged**
