### PR TITLE
Upgrade node and npm

### PR DESCRIPTION
**Pull request by nl0**
Set node@15 and npm@7 in package.json/engines, update lockfile format

### CODE REVIEW

**Comment by fiskus** [comment]
Hmmm, npm@7, really? Where can I find it? :)

**Comment by fiskus** [comment]
https://github.com/npm/npm/releases/tag/v6.1.0

Screenshot from 2020-12-08 14-24-54

**Comment by nl0** [comment]
> https://github.com/npm/npm/releases/tag/v6.1.0

> This repository has been archived by the owner. It is now read-only.

see the current official repo: https://github.com/npm/cli/releases

> Hmmm, npm@7, really? Where can I find it? :)

it's bundled with node@15, for example

**Comment by fiskus** [comment]
Weird, I have node v15, but npm v6

**Comment by nl0** [comment]
> Weird, I have node v15, but npm v6

maybe you're installing them separately

https://nodejs.org/en/download/releases/

Screenshot 2020-12-08 at 16 30 59

**Comment by fiskus** [comment]
npm v7 is still in testing for my ArchLinux
I'm going to install it via npm

**Review by fiskus — APPROVED** [review]
I didn't realize that node15 and npm7 are just one and a half months old.
Maybe it's too quick migration

**Pull request merged**
