### PR TITLE
Adopt `loglevel` lib

### PR DESCRIPTION
**Pull request by nl0**

### CODE REVIEW

**Review by fiskus — APPROVED** [review]
What is a plan to use it?

I really want to replace all console.log's with it as I proposed here https://github.com/quiltdata/quilt/pull/1882

**Comment by nl0** [comment]
> What is a plan to use it?

just use it everywhere you need any logging done =)

> I really want to replace all console.log's with it as I proposed here #1882

yeah that's the point

**Comment by fiskus** [comment]
I usually use https://www.npmjs.com/package/winston btw

**Comment by nl0** [comment]
> I usually use https://www.npmjs.com/package/winston btw

looks quite cool, but seems like an overkill for the catalog (tho would fit nicely into a node server if we ever need one)

**Pull request merged**
