### PR TITLE
quilt3-local: version bump

### PR DESCRIPTION
**Pull request by nl0**
update pillow

### CODE REVIEW

**Review by sir-sigurd — APPROVED** [review]
changelog?

**Comment by nl0** [comment]
> changelog?

we haven't started it yet for quilt3-local (i believe it should be separate)

**Comment by sir-sigurd** [comment]
> we haven't started it yet for quilt3-local (i believe it should be separate)

I think we also discussed putting quilt3-local into the separate repo...

**Comment by nl0** [comment]
> > we haven't started it yet for quilt3-local (i believe it should be separate)
> 
> I think we also discussed putting quilt3-local into the separate repo...

yeah, after the initial release -- so now is the time (when i get some capacity)

**Pull request merged**
