### PR TITLE
Discuss: Coding Standards guide

### PR DESCRIPTION
**Pull request by fiskus**
Guide for formatting and programming practices outside of ESLint scope. Logging rules is crucial to preserve healthy PR culture.

Ideal scenario: don't demand code changes when this isn't covered with this guide.

### CODE REVIEW

**Review by nl0 — COMMENTED** [review]
great idea. i'll try to get to this soonish and capture as many conventions as i can

**Comment by sir-sigurd** [comment]
How about adding CI job to ensure this?

**Comment by fiskus** [comment]
> How about adding CI job to ensure this?

Sure, we should automate everything we can. These rules are for something we can't or didn't yet automate.

**Comment by nl0** [comment]
> How about adding CI job to ensure this?

FYI we already have prettier and eslint in pre-commit hook

**Comment by fiskus** [comment]
Don't understand what's wrong with this PR. But it seems that it's not going to be approved

**Pull request closed without merging**
