### PR TITLE
FilesSelector: remove checkbox icon from select all / none btn

### PR DESCRIPTION
**Pull request by nl0**
- no items selected by default
- indeterminate state for "select all / none" checkbox when some items are selected

### CODE REVIEW

**Comment by fiskus** [comment]
I don't think the checkbox is confusing, Github has it :)

Screenshot from 2021-03-25 18-07-53

**Review by fiskus — APPROVED** [review]

**Comment by nl0** [comment]
> I don't think the checkbox is confusing, Github has it :)
> 
> Screenshot from 2021-03-25 18-07-53

maybe just my implementation is a little confusing, bc it shows the opposite (empty checkbox for "select none" btn when everything is selected)

**Review by fiskus — APPROVED** [review]

**Review by akarve — CHANGES_REQUESTED** [review]
Hi. I just spoke to the customer and played with the GH example. A few changes here:
* Leave the checkbox in (box is on the right)
* Default to unchecked
* unchecked text is "Select all"
* nice-to-have show "-" in box when "some" selected
* nice-to-have: text is "X selected" when 1 or more selected
* if you do handle "-" state, state machine is "-" clicks to "checked" clicks to "unchecked" clicked to "checked"

If you need to break this up into smaller pieces and backlog complex pieces, please do. Minimum viable solution would be these two states:
* [ ] Select all
* [x] Unselect all

**Comment by nl0** [comment]
> Hi. I just spoke to the customer and played with the GH example. One big change:
> 
>     * Default to NONE selected
> 
> 
> Rest of UX is fine. I will backlog emulation of GH checkbox.

ok, done

**Review by fiskus — APPROVED** [review]

**Pull request merged**
