### PR TITLE
use react-loadable

### PR DESCRIPTION
**Pull request by nl0**
use react-loadable wrappers for async component loading (depends on #464)

### CODE REVIEW

**Comment by akarve** [comment]
@nl0 can you rebase?

**Comment by nl0** [comment]
@akarve rebased

**Comment by akarve** [comment]
A few lint errors:
```
/Users/karve/code/quilt/catalog/app/components/UserMenu/index.js
  10:10  error  'mapProps' is defined but never used  no-unused-vars

/Users/karve/code/quilt/catalog/app/routes.js
   6:8   error  'get' is defined but never used  no-unused-vars
  14:48  error  Missing semicolon    
```

**Comment by akarve** [comment]
Tested on stage and looks good; I will merge after the lint errors are fixed

**Comment by nl0** [comment]
@akarve fixed

**Pull request merged**
