### PR TITLE
Make JsonDisplay nested keys lighter

### PR DESCRIPTION
**Pull request by fiskus**
Before:
1 before

After:
2 after

### CODE REVIEW

**Review by nl0 — APPROVED** [review]
looks ok, but i'm not quite sure why we're doing this

**Comment by fiskus** [comment]
I think it was hard to read the one-liner, when it's not obvious which key are from the first level, and which from the second

**Comment by fiskus** [comment]
Maybe, I'll wait feedback from customer who wanted these key/values (visually separated) in packages list

**Comment by fiskus** [comment]
Never heard since that anyone expressed interest in this.

**Pull request closed without merging**
