### PR TITLE
Reload file preview after file creation

### PR DESCRIPTION
**Pull request by fiskus**

### CODE REVIEW

**Review by nl0 — APPROVED** [review]

**Comment by fiskus** [comment]
Something doesn't work for versioned bucket

**Comment by fiskus** [comment]
@nl0 the same fix now works for both versioned and unversioned buckets

**Review by nl0 — APPROVED** [review]

**Comment by nl0** [comment]
@fiskus merging in?

**Comment by fiskus** [comment]
Yes, I didn't get notification over email

**Pull request merged**
