### PR TITLE
Move CSS files from app/ to app/assets/

### PR DESCRIPTION
**Pull request by fiskus**
* I think we can move favicon.ico and index.html there too
* `ipynb-styling/Makefile` doesn't work, maybe we can remove it, I don't know if it worths fixing

### CODE REVIEW

**Review by nl0 — APPROVED** [review]
what's the reasoning behind this?

**Comment by fiskus** [comment]
The reason is a clean root directory :) 
I want to add another theme for Perspective

**Comment by nl0** [comment]
> The reason is a clean root directory :) I want to add another theme for Perspective

mkay

**Comment by fiskus** [comment]
> it's needed for building (updating) ipynb styles, which we still rely on
I understand, but if it's broken, I think we don't depend on it really :)

This script uses `master` which went ahead, I suppose. Imported files are not there, no bower.json. We can `checkout` some tag or commit instead of `master to fix it

**Pull request merged**
