### PR TITLE
travis: bundle size monitoring

### PR DESCRIPTION
**Pull request by nl0**
monitor bundle size changes

### CODE REVIEW

**Comment by nl0** [comment]
doesn't work as intended yet

**Comment by nl0** [comment]
hm, nope, it does, actually.
@akarve rtm

**Comment by nl0** [comment]
@akarve look at the checks section:
 > bundlesize — Total bundle size is 654.54KB/null (-null)

it will show how the PRs affect bundle size

**Comment by akarve** [comment]
fine but do we need to set targets for it to be useful? or does it store past bundle sizes? it's just Xbk/null right now.

**Comment by nl0** [comment]
@akarve i dont see a point for setting targets in our case, just monitor the changes.

> does it store past bundle sizes? it's just Xbk/null right now.

yep, it should show how every PR affects bundle size

**Pull request merged**
