### PR TITLE
Update service role policy to include additional ecs, es and sqs permissions

### PR DESCRIPTION
**Pull request by robnewman**
# Description

# TODO

- [n/a] Unit tests
- [n/a] Automated tests (e.g. Preflight)
- [X] Confirm that this change meets security best practices and does not violate the security model
- [n/a] Documentation
    - [n/a] [Python: Run `build.py`](../gendocs/build.py) for new docstrings
    - [n/a] JavaScript: basic explanation and screenshot of new features
    - [n/a] Markdown somewhere in docs/**/*.md that explains the feature to end users (said .md files should be linked from SUMMARY.md so they appear on https://docs.quiltdata.com)
    - [n/a] Markdown docs for developers
- [n/a] [Changelog](CHANGELOG.md) entry (skip if change is not significant to end users, e.g. docs only)

### CODE REVIEW

**Review by sir-sigurd — COMMENTED** [review]
Permission changes look sane, other ones are controversial:

1. I don't think we should set `RoleName`. CloudFormation generates the sane one, but deals with possible conflicts.
2. I don't think we should set tags. Users can set tags for CloudFormation stack by themselves and they will are propagated to the role.

(if these changes come as separate focused PRs, I'd have already approved one related to permission)

**Review by dimaryaz — DISMISSED** [review]
Unfortunately, there are many many more permissions that we're missing. For example:

- `iam:CreatePolicyVersion`
- `s3:GetBucketOwnershipControls`
- `s3:PutBucketOwnershipControls`
- `s3:PutBucketPublicAccessBlock`
- `sns:CreateTopic`
- `sns:DeleteTopic`
- `sns:GetTopicAttributes`
- `sns:SetTopicAttributes`
- `synthetics:*`
- `kms:*`

I don't know of a good way to even find out all necessary permissions - I tried updating my stack over and over, and then looking at the error messages. I never figured out the specific permissions for `synthetics:*` or `kms:*` - and even then, that wasn't enough, and I ended up just adding `*:*`.

And finally, once you attach a role to a stack, there does not appear to be a way to remove it, short of deleting the stack.

So I think we should not recommend service roles at all.

**Comment by akarve** [comment]
This needs more thought and we can pull service roles from the docs until we have a working service role but at the same time we can’t ask for admin permissions as security and devops teams rightfully frown upon that. Maybe we backlog this but a starting place to make this tractable is to parse our own CFT and ask for * for every referenced service except IAM and then scope resources to things tagged “quilt”.

**Review by sir-sigurd — APPROVED** [review]

**Comment by drernie** [comment]
@sir-sigurd It looks like you approved this. Can we merge it?

**Comment by sir-sigurd** [comment]
> Can we merge it?

I'm OK with it

**Comment by drernie** [comment]
TODO: resolve conflict

**Comment by drernie** [comment]
Okay, I think this is clean but captures the new additions.  I have a vague memory of a 'kms:*' somewhere, but I don't see it, so hopefully the current setup is good.

**Comment by drernie** [comment]
@sir-sigurd Let me know if I should add back kms:* and synthetics:*. Otherwise, can you approve?

**Comment by drernie** [comment]
@sir-sigurd Any chance you can look at this before you go?

**Review by sir-sigurd — APPROVED** [review]

**Pull request merged**
