### PR TITLE
Merge pylint/pycodestyle and isort

### PR DESCRIPTION
**Pull request by dimaryaz**
No reason why pylint/pycodestyle should be one job, but isort should be separate.

### CODE REVIEW

**Review by sir-sigurd — COMMENTED** [review]
well, why not split them instead?

**Comment by nl0** [comment]
> well, why not split them instead?

yeah, at least in that case we'll have all the errors, not just the the first ones

**Comment by drernie** [comment]
@sir-sigurd Is this still worth doing? If not, can you close?

**Comment by drernie** [comment]
Not needed

**Pull request closed without merging**
