### PR TITLE
WIP: Implement full-text search for READMEs

### PR DESCRIPTION
**Pull request by dimaryaz**
Store a TSVECTOR of READMEs, with an index.
Search owner and name (as before) as well as the README.

TODO: Unit tests

### CODE REVIEW

**Comment by dimaryaz** [comment]
Here's a sample query and a query plan. It appears to be using indexes, but I don't know enough Postgres to tell if it's doing everything right.

```
packages=> EXPLAIN SELECT i.id AS i_id, i.owner AS i_owner, i.name AS i_name, i.is_public AS i_is_public, i.is_team AS i_is_team, r.readme AS r_readme, ts_rank_cd((setweight(to_tsvector(i.owner), 'A') || setweight(to_tsvector(i.name), 'A')) || coalesce(r.preview_tsv, ''), i.query, 32) AS rank FROM (SELECT instance.id AS id, package.owner AS owner, package.name AS name, bool_or(access."user" = 'public') AS is_public, bool_or(access."user" = 'team') AS is_team, plainto_tsquery('dima') AS query FROM instance JOIN package ON package.id = instance.package_id JOIN access ON package.id = access.package_id JOIN tag ON instance.id = tag.instance_id WHERE access."user" IN ('dima', 'public') AND tag.tag = 'latest' GROUP BY package.id, instance.id) AS i LEFT OUTER JOIN (SELECT instance.id AS id, s3_blob.preview_tsv AS preview_tsv, substr(s3_blob.preview, 1, 100) AS readme FROM instance JOIN instance_blob AS instance_blob_1 ON instance.id = instance_blob_1.instance_id JOIN s3_blob ON s3_blob.id = instance_blob_1.blob_id WHERE (((((instance.contents -> 'children') -> 'README') -> 'hashes')) ->> 0) = s3_blob.hash) AS r ON i.id = r.id WHERE (r.preview_tsv @@ i.query) OR ((to_tsvector(i.owner) || to_tsvector(i.name)) @@ i.query) ORDER BY rank DESC, i.owner, i.name;
                                                                                                                                 QUERY PLAN                                                  
                                                                                
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 Sort  (cost=447.29..447.30 rows=1 width=338)
   Sort Key: (ts_rank_cd(((setweight(to_tsvector((package.owner)::text), 'A'::"char") || setweight(to_tsvector((package.name)::text), 'A'::"char")) || COALESCE(s3_blob.preview_tsv, ''::tsve
ctor)), (plainto_tsquery('dima'::text)), 32)) DESC, package.owner, package.name
   ->  Nested Loop Left Join  (cost=7.49..447.28 rows=1 width=338)
         Filter: ((s3_blob.preview_tsv @@ (plainto_tsquery('dima'::text))) OR ((to_tsvector((package.owner)::text) || to_tsvector((package.name)::text)) @@ (plainto_tsquery('dima'::text))))
         ->  GroupAggregate  (cost=6.64..6.92 rows=1 width=342)
               Group Key: package.id, instance_1.id
               ->  Sort  (cost=6.64..6.64 rows=1 width=454)
                     Sort Key: package.id, instance_1.id
                     ->  Nested Loop  (cost=1.61..6.63 rows=1 width=454)
                           Join Filter: (instance_1.id = tag.instance_id)
                           ->  Seq Scan on tag  (cost=0.00..1.27 rows=1 width=8)
                                 Filter: ((tag)::text = 'latest'::text)
                           ->  Nested Loop  (cost=1.61..5.30 rows=4 width=454)
                                 ->  Hash Join  (cost=1.47..2.79 rows=2 width=454)
                                       Hash Cond: (package.id = access.package_id)
                                       ->  Seq Scan on package  (cost=0.00..1.22 rows=22 width=300)
                                       ->  Hash  (cost=1.45..1.45 rows=2 width=154)
                                             ->  Seq Scan on access  (cost=0.00..1.45 rows=2 width=154)
                                                   Filter: (("user")::text = ANY ('{dima,public}'::text[]))
                                 ->  Index Scan using idx_hash on instance instance_1  (cost=0.14..1.25 rows=1 width=16)
                                       Index Cond: (package_id = package.id)
         ->  Nested Loop  (cost=0.85..439.32 rows=1 width=787)
               ->  Nested Loop  (cost=0.56..431.70 rows=1 width=795)
                     ->  Index Scan using instance_pkey on instance  (cost=0.14..8.16 rows=1 width=40)
                           Index Cond: (instance_1.id = id)
                     ->  Index Scan using idx on s3_blob  (cost=0.42..423.53 rows=1 width=852)
                           Index Cond: ((hash)::text = ((((instance.contents -> 'children'::text) -> 'README'::text) -> 'hashes'::text) ->> 0))
               ->  Index Only Scan using pk_instance_blob on instance_blob instance_blob_1  (cost=0.29..7.61 rows=1 width=16)
                     Index Cond: ((instance_id = instance.id) AND (blob_id = s3_blob.id))
(29 rows)
```

**Comment by dimaryaz** [comment]
Actually, no, something is not right. A simple FTS query mentions the `idx_tsv` index:
```
packages=> explain select preview from s3_blob where (preview_tsv @@ plainto_tsquery('quilt'));
                              QUERY PLAN                               
-----------------------------------------------------------------------
 Bitmap Heap Scan on s3_blob  (cost=12.27..24.59 rows=3 width=354)
   Recheck Cond: (preview_tsv @@ plainto_tsquery('quilt'::text))
   ->  Bitmap Index Scan on idx_tsv  (cost=0.00..12.27 rows=3 width=0)
         Index Cond: (preview_tsv @@ plainto_tsquery('quilt'::text))
(4 rows)
```

But the big query does not. I'll look into this - unless any of you Postgres experts have ideas?

**Comment by asah** [comment]
Yes, I know about postgres quiet optimization and will look into this.

**Comment by asah** [comment]
@dimaryaz 

update: for the second query, AFAICT the index is working as intended.  Do you want me to look into the first query?

~80 msec  with the initial set of 38,453 rows.
~80 msec  after I duplicated the data 64x to 2.5M rows and re-created the indices.


[packages] # create table s3_blob_scaletest as select * from s3_blob;
SELECT 38453
Time: 169.017 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 38453
Time: 178.465 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 76906
Time: 453.261 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 153812
Time: 733.339 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 307624
Time: 1546.623 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 615248
Time: 4282.904 ms
[packages] # insert into s3_blob_scaletest select id+(select max(id) from s3_blob_scaletest), owner, hash, size, preview, preview_tsv from s3_blob_scaletest ;
INSERT 0 1230496
Time: 9406.449 ms
[packages] # select regexp_replace(regexp_replace(pg_get_indexdef(idx.oid)||';', 'INDEX ', 'INDEX s3_blob_scaletest__'), 's3_blob ', 's3_blob_scaletest ')
from pg_index ind
  join pg_class idx on idx.oid = ind.indexrelid
  join pg_class tbl on tbl.oid = ind.indrelid
  left join pg_namespace ns on ns.oid = tbl.relnamespace
where tbl.relname = 's3_blob'
   and ns.nspname = 'public';
                                       regexp_replace
--------------------------------------------------------------------------------------------
 CREATE UNIQUE INDEX s3_blob_scaletest__s3_blob_pkey ON s3_blob_scaletest USING btree (id);
 CREATE UNIQUE INDEX s3_blob_scaletest__idx ON s3_blob_scaletest USING btree (owner, hash);
 CREATE INDEX s3_blob_scaletest__idx_tsv ON s3_blob_scaletest USING gin (preview_tsv);
(3 rows)

Time: 82.594 ms
[packages] #  CREATE UNIQUE INDEX s3_blob_scaletest__s3_blob_pkey ON s3_blob_scaletest USING btree (id);
 CREATE UNIQUE INDEX s3_blob_scaletest__idx ON s3_blob_scaletest USING btree (owner, hash);
 CREATE INDEX s3_blob_scaletest__idx_tsv ON s3_blob_scaletest USING gin (preview_tsv);
CREATE INDEX
Time: 3016.308 ms
[packages] #  CREATE UNIQUE INDEX s3_blob_scaletest__idx ON s3_blob_scaletest USING btree (owner, hash);
ERROR:  23505: could not create unique index "s3_blob_scaletest__idx"
DETAIL:  Key (owner, hash)=(dima, 54f1040eced60ae4fce800fb9d0130675e81a775975d35349b1214450ad024eb) is duplicated.
SCHEMA NAME:  public
TABLE NAME:  s3_blob_scaletest
CONSTRAINT NAME:  s3_blob_scaletest__idx
LOCATION:  comparetup_index_btree, tuplesort.c:4484
Time: 225.357 ms
[packages] #  CREATE INDEX s3_blob_scaletest__idx_tsv ON s3_blob_scaletest USING gin (preview_tsv);
CREATE INDEX
Time: 907.370 ms
[packages] # explain select count(*) from (select preview from s3_blob_scaletest where (preview_tsv @@ plainto_tsquery('quilt')))t;
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Aggregate  (cost=679.43..679.44 rows=1 width=8)
   ->  Bitmap Heap Scan on s3_blob_scaletest  (cost=13.52..679.02 rows=164 width=0)
         Recheck Cond: (preview_tsv @@ plainto_tsquery('quilt'::text))
         ->  Bitmap Index Scan on s3_blob_scaletest__idx_tsv  (cost=0.00..13.48 rows=164 width=0)
               Index Cond: (preview_tsv @@ plainto_tsquery('quilt'::text))
(5 rows)

Time: 75.062 ms
[packages] # select count(*) from (select preview from s3_blob_scaletest where (preview_tsv @@ plainto_tsquery('quilt')))t;
 count
-------
   192
(1 row)

Time: 75.398 ms

**Comment by asah** [comment]
@dimaryaz  and I discussed the first query live... turns out it's kind of a pain to index JSONB navigation queries, even using an expression index (query optimizer didn't use the index...), e.g. create index instance_scaletest__readme_hash_idx on instance_scaletest using GIN ((((instance_scaletest.contents -> 'children'::text) -> 'README'::text) -> 'hashes'::text));

Instead, it looks like a materialized view-column works better.

[packages] # alter table instance_scaletest add column readme_blobid bigint;
ALTER TABLE
Time: 79.284 ms
[packages] # update instance_scaletest set readme_blobid = s3_blob.id from s3_blob where (((((instance_scaletest.contents -> 'children') -> 'README') -> 'hashes')) ->> 0) = s3_blob.hash;
UPDATE 5120
Time: 6646.398 ms
[packages] # explain select count(*) from (SELECT instance.id AS id,
         s3_blob.preview_tsv AS preview_tsv,
         substr(s3_blob.preview, 1, 100) AS readme
  FROM instance_scaletest as INSTANCE
  JOIN instance_blob AS instance_blob_1 ON instance.id = instance_blob_1.instance_id
  JOIN s3_blob ON s3_blob.id = instance_blob_1.blob_id
  where instance.readme_blobid = s3_blob.id
)t;
                                                                 QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------
Aggregate  (cost=2256.01..2256.02 rows=1 width=8)
  ->  Nested Loop  (cost=0.86..2256.01 rows=1 width=0)
        ->  Merge Join  (cost=0.57..2255.67 rows=1 width=16)
              Merge Cond: (instance.id = instance_blob_1.instance_id)
              Join Filter: (instance.readme_blobid = instance_blob_1.blob_id)
              ->  Index Scan using instance_scaletest__instance_pkey on instance_scaletest instance  (cost=0.28..4253.75 rows=7680 width=16)
              ->  Index Only Scan using pk_instance_blob on instance_blob instance_blob_1  (cost=0.29..1663.13 rows=38445 width=16)
        ->  Index Only Scan using s3_blob_pkey on s3_blob  (cost=0.29..0.33 rows=1 width=8)
              Index Cond: (id = instance_blob_1.blob_id)
(9 rows)

Time: 76.425 ms

# select count(*) from (SELECT instance.id AS id,
          s3_blob.preview_tsv AS preview_tsv,
          substr(s3_blob.preview, 1, 100) AS readme
   FROM instance_scaletest as INSTANCE
   JOIN instance_blob AS instance_blob_1 ON instance.id = instance_blob_1.instance_id
   JOIN s3_blob ON s3_blob.id = instance_blob_1.blob_id
   where instance.readme_blobid = s3_blob.id
)t;
 count
-------
    20
(1 row)

Time: 121.336 ms

[packages] # explain select count(*) from (SELECT instance.id AS id,
... #           s3_blob.preview_tsv AS preview_tsv,
... #           substr(s3_blob.preview, 1, 100) AS readme
... #    FROM instance_scaletest as INSTANCE
... #    JOIN instance_blob AS instance_blob_1 ON instance.id = instance_blob_1.instance_id
... #    JOIN s3_blob ON s3_blob.id = instance_blob_1.blob_id
... #    WHERE (((((instance.contents -> 'children') -> 'README') -> 'hashes')) ->> 0) = s3_blob.hash
... # )t;
                                                                   QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=7020.02..7020.03 rows=1 width=8)
   ->  Hash Join  (cost=6139.22..7020.01 rows=1 width=0)
         Hash Cond: ((instance_blob_1.instance_id = instance.id) AND (instance_blob_1.blob_id = s3_blob.id))
         ->  Seq Scan on instance_blob instance_blob_1  (cost=0.00..592.45 rows=38445 width=16)
         ->  Hash  (cost=6050.40..6050.40 rows=5921 width=16)
               ->  Hash Join  (cost=2456.19..6050.40 rows=5921 width=16)
                     Hash Cond: (((((instance.contents -> 'children'::text) -> 'README'::text) -> 'hashes'::text) ->> 0) = (s3_blob.hash)::text)
                     ->  Seq Scan on instance_scaletest instance  (cost=0.00..1622.80 rows=7680 width=643)
                     ->  Hash  (cost=1486.53..1486.53 rows=38453 width=73)
                           ->  Seq Scan on s3_blob  (cost=0.00..1486.53 rows=38453 width=73)
(10 rows)

Time: 80.264 ms
[packages] # select count(*) from (SELECT instance.id AS id,
          s3_blob.preview_tsv AS preview_tsv,
          substr(s3_blob.preview, 1, 100) AS readme
   FROM instance_scaletest as INSTANCE
   JOIN instance_blob AS instance_blob_1 ON instance.id = instance_blob_1.instance_id
   JOIN s3_blob ON s3_blob.id = instance_blob_1.blob_id
   WHERE (((((instance.contents -> 'children') -> 'README') -> 'hashes')) ->> 0) = s3_blob.hash
)t;

 count
-------
    20
(1 row)

Time: 8464.955 ms

==> ~70x faster

**Pull request closed without merging**
