### PR TITLE
User page

### PR DESCRIPTION
**Pull request by nl0**
User page. Branched off of #313, so shouldn't be merged before it.
@akarve @asah pls review

## Questions:

- [x] now the api returns ok response (with empty package list) even if the user doesn't exist -- is it ok or should we check it somehow and show some "user doesn't exist" message?
- [x] should we show something else on the page? task description in asana suggests that there should be "browse all packages" link and gallery, is that right?

### CODE REVIEW

**Comment by akarve** [comment]
@nl0 
* for the time being go ahead and handle the error (even if it doesn't occur) e.g. as we do in containers/App/sagas.js in `doGetPackage`; and make sure the component handles the error condition using the existing classes (e.g. [this link](https://quiltdata.com/package/uciml/iriss) for a package that doesn't exist)
* just list the packages for now. page title should be Packages owned by `username`

**Comment by akarve** [comment]
@nl0 also, if the list is empty, do something [like this](https://quiltdata.com/search/?q=asdfasdf). I believe PackageList provides a default string for that (it should, anyway).

**Comment by nl0** [comment]
@akarve 
> for the time being go ahead and handle the error (even if it doesn't occur) e.g. as we do in containers/App/sagas.js in doGetPackage; and make sure the component renders the error condition using the existing classes (e.g. this link for a package that doesn't exist)

the error is handled properly on the front-end, but the thing is that the api doesn't return error for the non-existent user, it just returns an empty package list, which doesn't seem correct.

> also, if the list is empty, do something like this. I believe PackageList provides a default string for that (it should, anyway).

`PackageList` already does this (it says "Nothin here yet").

**Comment by nl0** [comment]
> page title should be Packages owned by username

done

**Comment by nl0** [comment]
i'll rebase this and double-check if everything's ok

**Comment by akarve** [comment]
@nl0 branch is approved but you'll need to resolve the conflicts before i can merge

**Comment by akarve** [comment]
BTW - API is behaving as expected; please still test the failure case (`status !== 200`) and error chain, but for now it's OK if API is 200 even if user doesn't exist.

**Comment by nl0** [comment]
@akarve ready. As with #302, this PR is incompatible with #326, so if one is merged, the other one should be adjusted before merging.

**Pull request merged**
