### PR TITLE
Send catalog release hash to mixpanel

### PR DESCRIPTION
**Pull request by nl0**

### CODE REVIEW

**Review by kevinemoore — COMMENTED** [review]
I recommend we close this PR in favor of one that sends the template hash. I assume that's more difficult?

**Comment by nl0** [comment]
> I recommend we close this PR in favor of one that sends the template hash. I assume that's more difficult?

yeah it is, we need to pass the template hash to the catalog container and then expose it

**Comment by akarve** [comment]
Well we can still merge this and backlog the deployment hash. There's no reason not to have this info imo. What about sentry?

**Comment by nl0** [comment]
> What about sentry?

it has this data if you're asking that

**Pull request merged**
