### PR TITLE
Package metadata display

### PR DESCRIPTION
**Pull request by nl0**
### TODO
- [x] partially expand (tease) meta section

### CODE REVIEW

**Review by akarve — COMMENTED** [review]
Looks good; can we add a teased metadata panel to the package root or do you want to do that in a separate change set?

**Comment by nl0** [comment]
> can we add a teased metadata panel to the package root

@akarve it's already there (should work with the recent fix)

**Review by akarve — COMMENTED** [review]
Cool and I'm approving but please make this change first (if it's not a big deal). Instead of displaying the number of top-level keys can you auto-expand the top-level group (example below; that's how it should start)? it will be much more discoverable that way. and, if possible, instead of showing the number of keys in an unexpanded section, we should show the key names themselves (if it's easy).

Screen Shot 2020-09-21 at 18 52 30

**Comment by nl0** [comment]
> Cool and I'm approving but please make this change first (if it's not a big deal). Instead of displaying the number of top-level keys can you auto-expand the top-level group (example below; that's how it should start)? it will be much more discoverable that way. and, if possible, instead of showing the number of keys in an unexpanded section, we should show the key names themselves (if it's easy).

@akarve done

**Review by akarve — APPROVED** [review]

**Pull request merged**
