### PR TITLE
Use promises for URLs in IGV to have fresh signing each time they used

### PR DESCRIPTION
**Pull request by fiskus**
- [x] [Changelog](../tree/master/docs/CHANGELOG.md) entry (skip if change is not significant to end users, e.g. docs only)

### CODE REVIEW

**Review by nl0 — DISMISSED** [review]
i don't quite get it -- is IGV able to accept async thunks instead of strings as URLs?

**Comment by fiskus** [comment]
> is IGV able to accept async thunks instead of strings as URLs?

Yes, it is. Sorry, I didn't add this to the PR description.
They use their own helper module for every URL (though in documentation they said only about `tracks` URLs), and it nailed down to that function where it is a check if URL is a string or a function, and those functions or strings could be `async`:
https://github.com/igvteam/igv-utils/blob/master/src/igvxhr.js#L91

**Comment by fiskus** [comment]
I can pass thunks but if `indexURL` or `indexFile` is omitted, they try to guess it, and it produces invalid URL like `function(){}.fai`. I filed a bug and fix https://github.com/igvteam/igv.js/pull/1821
Hope they accept it, so I can remove our hacky fix.

**Comment by nl0** [comment]
> Hope they accept it

looks like they did. not sure when they're going to cut their next release tho

**Review by nl0 — APPROVED** [review]

**Pull request merged**
