### PR TITLE
Bump mod_zip: allow empty zip files

### PR DESCRIPTION
**Pull request by dimaryaz**
See https://github.com/quiltdata/mod_zip/commit/979314cca0507a59071310f09401861cced73ccb

Will make the registry code simpler.

### CODE REVIEW

**Review by sir-sigurd — APPROVED** [review]
I'd prefer to avoid drifts from upstream, unless we don't have other choice.

**Comment by robnewman** [comment]
@dimaryaz @sir-sigurd Can we cleanly merge this with `master` and deploy?

**Comment by robnewman** [comment]
@dimaryaz @sir-sigurd Can we get this merged with `master` and squashed?

**Comment by dimaryaz** [comment]
Oh, forgot about this one. But actually, my fixes got merged upstream, so let me test it and see if everything works.

**Comment by dimaryaz** [comment]
Actually, the other two patches got upstreamed, but I haven't sent out this one. Hopefully, this one will make it someday, too.

**Pull request merged**
