### PR TITLE
Quilt3 search

### PR DESCRIPTION
**Pull request by drernie**
Switch quilt3.search to use registryUrl instead of apiGateway

### CODE REVIEW

**Comment by drernie** [comment]
So, I can get it to call the registryUrl, but now I get an odd error. Even after I ensure the input is the same as on the ES page.  Is this an auth problem?

```python
>>> from quilt3 import search
>>> results = search("tes")
https://nightly-registry.quilttest.com/search?index=%2A&action=search&query=%2A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ernest/GitHub/quilt/api/python/quilt3/telemetry.py", line 135, in decorated
    results = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ernest/GitHub/quilt/api/python/quilt3/api.py", line 200, in search
    raw_results = search_api(query, '*', limit)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ernest/GitHub/quilt/api/python/quilt3/search_util.py", line 53, in search_api
    raise QuiltException(response.text)
quilt3.util.QuiltException: {"errors":[{"message":"Token could not be deserialized"}],"message":"Token could not be deserialized"}
```

**Comment by drernie** [comment]
Doh. I see I rediscovered what you were doing on https://github.com/quiltdata/quilt/pull/3448. Did you get the same error I did?

**Comment by sir-sigurd** [comment]
> Did you get the same error I did?

no

**Comment by drernie** [comment]
Closing this in favor of https://github.com/quiltdata/quilt/pull/3448#pullrequestreview-2016620302

**Pull request closed without merging**
