### PR TITLE
Fix saving dataframes and files when saving a package

### PR DESCRIPTION
**Pull request by dimaryaz**

### CODE REVIEW

**Comment by dimaryaz** [comment]
Huh, it's failing to read the data in the existing package. I think we've seen this bug before. Also, it should be reproduceable without building a new package - but just by reading the old one.

The regression is the fact that before, `quilt.build` only saved the JSON, and didn't touch dataframes at all; now it's saving all of the dataframes (even the unchanged ones, since there's no way to know). Technically, I could skip saving the nodes that were never _read_, since were obviously not modified - though then it's a little weird that some objects get overwritten and not others.

**Comment by dimaryaz** [comment]
Yeah... Unfortunately, the package is corrupted (or `pytables` just sucks). Easy repro in master:

```
In [5]: from quilt.data.akarve import clinton_email

In [6]: clinton_email.aliases.data()
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-3ceadb8ed311> in <module>()
----> 1 clinton_email.aliases.data()
...
```

**Comment by dimaryaz** [comment]
(And it works in Python2 - but not Python3)

**Comment by akarve** [comment]
OK Interesting. If I rebuild in 3.6 the problem goes away in 3.6 but I get another problem in 2.7 (below). Rebuilding in 2.7 also

# Load 3.6 package in 2.7:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-25b8ecb6c7b2> in <module>()
----> 1 from quilt.data.akarve import clinton_email

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/data.pyc in find_module(fullname, path)
    176         elif len(parts) == 2:
    177             user, package = parts
--> 178             pkgobj = PackageStore.find_package(user, package)
    179             if pkgobj:
    180                 file_path = pkgobj.get_path()

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/tools/store.pyc in find_package(cls, user, package, start_dir)
     70         for store_dir in dirs:
     71             store = PackageStore(store_dir)
---> 72             pkg = store.get_package(user, package)
     73             if pkg is not None:
     74                 return pkg

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/tools/store.pyc in get_package(self, user, package)
     94                 user=user,
     95                 package=package,
---> 96                 path=path
     97             )
     98         return None

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/tools/package.pyc in __init__(self, store, user, package, path, contents)
     78 
     79         if contents is None:
---> 80             contents = self._load_contents()
     81 
     82         self._contents = contents

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/tools/package.pyc in _load_contents(self)
     84     def _load_contents(self):
     85         with open(self._path, 'r') as contents_file:
---> 86             contents = json.load(contents_file, object_hook=decode_node)
     87             if not isinstance(contents, RootNode):
     88                 contents = RootNode(contents.children, PackageFormat.default.value)

/Users/karve/anaconda3/envs/py27/lib/python2.7/json/__init__.pyc in load(fp, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    289         parse_float=parse_float, parse_int=parse_int,
    290         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook,
--> 291         **kw)
    292 
    293 

/Users/karve/anaconda3/envs/py27/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    350     if parse_constant is not None:
    351         kw['parse_constant'] = parse_constant
--> 352     return cls(encoding=encoding, **kw).decode(s)

/Users/karve/anaconda3/envs/py27/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    362 
    363         """
--> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    365         end = _w(s, end).end()
    366         if end != len(s):

/Users/karve/anaconda3/envs/py27/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    378         """
    379         try:
--> 380             obj, end = self.scan_once(s, idx)
    381         except StopIteration:
    382             raise ValueError("No JSON object could be decoded")

/Users/karve/anaconda3/envs/py27/lib/python2.7/site-packages/quilt/tools/core.pyc in decode_node(value)
     86         return value
     87     node_cls = NODE_TYPE_TO_CLASS[type_str]
---> 88     return node_cls(**value)
     89 
     90 def hash_contents(contents):

TypeError: __init__() got an unexpected keyword argument 'format'
```

# Load 2.7 package in 3.6
```
In [2]: clinton_email.aliases()
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-29b16d3b959c> in <module>()
----> 1 clinton_email.aliases()

/Users/karve/code/quilt/quilt/data.py in __call__(self)
    106 
    107     def __call__(self):
--> 108         return self.data()
    109 
    110     def data(self):

/Users/karve/code/quilt/quilt/data.py in data(self)
    112         Returns the contents of the node: a dataframe or a file path.
    113         """
--> 114         return self._package.get_obj(self._node)
    115 
    116     def _to_core_node(self):

/Users/karve/code/quilt/quilt/tools/package.py in get_obj(self, node)
    216         """
    217         if isinstance(node, TableNode):
--> 218             return self._dataframe(node.hashes, node.format)
    219         elif isinstance(node, FileNode):
    220             return self.file(node.hashes)

/Users/karve/code/quilt/quilt/tools/package.py in _dataframe(self, hash_list, pkgformat)
    126         enumformat = PackageFormat(pkgformat)
    127         if enumformat is PackageFormat.HDF5:
--> 128             return self._read_hdf5(hash_list)
    129         elif enumformat is PackageFormat.PARQUET:
    130             parqlib = self.get_parquet_lib()

/Users/karve/code/quilt/quilt/tools/package.py in _read_hdf5(self, hash_list)
    101         filehash = hash_list[0]
    102         with pd.HDFStore(self._store.object_path(filehash), 'r') as store:
--> 103             return store.get(self.DF_NAME)
    104 
    105     def _read_parquet_arrow(self, hash_list):

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/pandas/io/pytables.py in get(self, key)
    674         if group is None:
    675             raise KeyError('No object named %s in the file' % key)
--> 676         return self._read_group(group)
    677 
    678     def select(self, key, where=None, start=None, stop=None, columns=None,

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/pandas/io/pytables.py in _read_group(self, group, **kwargs)
   1319         s = self._create_storer(group)
   1320         s.infer_axes()
-> 1321         return s.read(**kwargs)
   1322 
   1323 

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/pandas/io/pytables.py in read(self, start, stop, **kwargs)
   2864             blk_items = self.read_index('block%d_items' % i)
   2865             values = self.read_array('block%d_values' % i,
-> 2866                                      start=_start, stop=_stop)
   2867             blk = make_block(values,
   2868                              placement=items.get_indexer(blk_items))

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/pandas/io/pytables.py in read_array(self, key, start, stop)
   2413         import tables
   2414         node = getattr(self.group, key)
-> 2415         data = node[start:stop]
   2416         attrs = node._v_attrs
   2417 

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/tables/vlarray.py in __getitem__(self, key)
    673             start, stop, step = self._process_range(
    674                 key.start, key.stop, key.step)
--> 675             return self.read(start, stop, step)
    676         # Try with a boolean or point selection
    677         elif type(key) in (list, tuple) or isinstance(key, numpy.ndarray):

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/tables/vlarray.py in read(self, start, stop, step)
    813         atom = self.atom
    814         if not hasattr(atom, 'size'):  # it is a pseudo-atom
--> 815             outlistarr = [atom.fromarray(arr) for arr in listarr]
    816         else:
    817             # Convert the list to the right flavor

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/tables/vlarray.py in <listcomp>(.0)
    813         atom = self.atom
    814         if not hasattr(atom, 'size'):  # it is a pseudo-atom
--> 815             outlistarr = [atom.fromarray(arr) for arr in listarr]
    816         else:
    817             # Convert the list to the right flavor

/Users/karve/anaconda3/envs/dev/lib/python3.6/site-packages/tables/atom.py in fromarray(self, array)
   1226         if array.size == 0:
   1227             return None
-> 1228         return six.moves.cPickle.loads(array.tostring())

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)
```

**Comment by akarve** [comment]
fixed with top of tree quilt ff03141

**Pull request merged**
